server {
        listen      5001;
        server_name 127.0.0.1;
        client_max_body_size 200M;
        gzip on;
        gzip_min_length 1k;
        gzip_buffers 4 16k;
        gzip_comp_level 4;
        gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript image/jpeg image/gif image/png;
        gzip_vary off;
        gzip_disable "MSIE [1-6]\.";
        index index.php index.html index.htm;

        # aiap服务端映射
        location /api/aiap/v1/ {
            proxy_pass http://10.252.26.5:30925/api/aiap/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept "application/json";
            proxy_cookie_path /api/aiap/v1 /api/aiap/v1; # cookie转发
        }

        # AIMDP服务端映射
        location /api/aimdp/v1/ {
            proxy_pass http://10.252.26.5:30183/api/aimdp/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept "application/json";
            proxy_cookie_path /api/aimdp/v1 /api/aimdp/v1; # cookie转发
        }    


        # 工作流服务端映射
        location /api/aimdp/v1/workflow {
            proxy_pass http://10.252.26.5:30888/api/aimdp/v1/workflow;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept "application/json";
            proxy_cookie_path /api/aimdp/v1 /api/aimdp/v1; # cookie转发
        } 

        # 作业列表服务端映射
        location /api/aimdp/v1/workflow_instance {
            proxy_pass http://10.252.26.5:30888/api/aimdp/v1/workflow_instance;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept "application/json";
            proxy_cookie_path /api/aimdp/v1 /api/aimdp/v1; # cookie转发
        } 

        # AUTH服务端映射
        location /api/auth/v1/ {
            proxy_pass http://10.252.26.5:31635/api/auth/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept "application/json";
            proxy_cookie_path /api/auth/v1 /api/auth/v1; # cookie转发
        }     

	# 前端路径映射
        location / {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS,DELETE,PUT,HEAD";
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html =404;
            if ($request_filename ~* .*\.(?:htm|html)$){
                expires -1s;
                add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
            }
            if ($request_filename ~* .*\.(?:js|css)$)
            {
                expires 30d;
            }
            if ($request_filename ~* .*\.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm)$)
            {
                expires 30d;
            }
        }
}
